service: momo-aws-email
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    EMAIL_USER: davidvalenzuela@tecnopac.com.co
    EMAIL_PASSWORD: David2024.
    EMAIL_SMTP: smtp.hostinger.com
    DB_HOST: momo-coffe.cflkp1qysre8.us-east-1.rds.amazonaws.com
    DB_NAME: postgres
    DB_USER: momouserdatabase
    DB_PASSWORD: momo2024!
    DB_PORT: 5432
  region: us-east-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
