service: momo-aws-email
frameworkVersion: '3'
	
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1


functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-api-stage

custom:
  apiStage:
    variables:
      stage: ${opt:stage, self:provider.stage}
