service: momo-aws-email
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    EMAIL_USER: davidvalenzuela@tecnopac.com.co
    EMAIL_PASSWORD: David2024.
    EMAIL_SMTP: smtp.hostinger.com
   
functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
  - serverless-stage-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  stages: # Define the stages array here
    - dev
    - prod

stages:
  dev:
    environment:
      # Override DB_HOST for dev stage
      DB_HOST: momo-dev-instance-1-us-east-1b.c9oa4s8sguow.us-east-1.rds.amazonaws.com
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: momocafe2024!
      DB_PORT: 5432
    variables:
      stageVar: dev
  prod:
    environment:
      # Override DB_HOST for prod stage
      DB_HOST: momo-db-instance-1-us-east-1c.c9oa4s8sguow.us-east-1.rds.amazonaws.com
      DB_NAME: postgres
      DB_USER: momo2024mx
      DB_PASSWORD: momocafe2024!
      DB_PORT: 5432
    variables:
      stageVar: prod
